---
- name: ping the host
  hosts: servers
  remote_user: root
  gather_facts: False

  vars:
    ansible_ssh_private_key_file: "{{ lookup('env','SSH_KEY_FILE') }}"
  tasks:
    - name: Check we can access the host
      ping:

    - name: Run apt update
      become: true
      become_user: root
      shell: apt update -y

    - name: Create acserver group
      group:
        name: acserver
        state: present

    - name: Create a login user
      user:
        name: acserver
        groups: acserver 
        state: present
        system: yes

    - name: Download linuxgsm.sh
      become_user: acserver
      become: true
      ansible.builtin.get_url:
        url: https://linuxgsm.sh
        dest: /home/acserver/linuxgsm.sh
        mode: '0740'

    - name: Run linuxgsm.sh to install server
      become_user: acserver
      become: true
      ansible.builtin.shell:
        cmd: ./linuxgsm.sh acserver
        chdir: /home/acserver