---
- name: ping the host
  hosts: servers
  remote_user: root
  gather_facts: False

  vars:
    ansible_ssh_private_key_file: "{{ lookup('env','SSH_KEY_FILE') }}"
  tasks:
    - name: Check we can access the host
      ping:

    - name: Run apt update
      become: true
      become_user: root
      shell: apt update -y

    - name: Create acserver group
      group:
        name: acserver
        state: present

    - name: Create a login user
      user:
        name: acserver
        groups: acserver 
        state: present
        system: yes